"""add refresh token expiry warning marker

Revision ID: 4777431c41e3
Revises: 20260609b001
Create Date: 2026-06-09 21:00:10.653017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4777431c41e3'
down_revision: Union[str, Sequence[str], None] = '20260609b001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_expiry_warning_sent_for', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('refresh_token_expiry_warning_sent_for')

    # ### end Alembic commands ###
