"""search run counts

Revision ID: 99296b4cc4ff
Revises: c75528720d4f
Create Date: 2026-06-10 00:06:49.097836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99296b4cc4ff'
down_revision: Union[str, Sequence[str], None] = 'c75528720d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fetched_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_judged_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.drop_column('last_judged_count')
        batch_op.drop_column('last_fetched_count')

    # ### end Alembic commands ###
