"""add ai_judge_image_max_px

Revision ID: f7e5959f917c
Revises: 8f9a0b1c2d3e
Create Date: 2026-06-20 00:34:07.719305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e5959f917c'
down_revision: Union[str, Sequence[str], None] = '8f9a0b1c2d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_judge_image_max_px', sa.Integer(), nullable=False, server_default='512'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('ai_judge_image_max_px')

    # ### end Alembic commands ###
